import type { DashboardRequestMetricsInput } from "@/lib/types/dashboardMetrics";
import type { PricingGroupMonitorStatusInput } from "@/lib/types/pricingMonitoring";

export const queryKeys = {
  settings: ["settings"] as const,
  proxyStatus: ["proxyStatus"] as const,
  requestLogs: ["requestLogs"] as const,
  dashboardLiveRequestMetrics: (input: DashboardRequestMetricsInput) =>
    [
      "dashboardRequestMetrics",
      "live",
      1,
      input.localDayStartMs,
      input.localDayEndMs,
    ] as const,
  dashboardCumulativeRequestMetrics: ["dashboardRequestMetrics", "cumulative", 1] as const,
  stations: ["stations"] as const,
  stationAssets: ["stationAssets"] as const,
  stationAssetsForStations: (stationIds: readonly string[]) =>
    ["stationAssets", "stations", stationIds] as const,
  stationAsset: (stationId: string) => ["stationAssets", stationId] as const,
  collectorSnapshots: (stationId: string) => ["collectorSnapshots", stationId] as const,
  collectorRuns: (stationId: string) => ["collectorRuns", stationId] as const,
  stationPublishedStatusRoot: ["stationPublishedStatus"] as const,
  stationPublishedStatus: (stationId: string) => ["stationPublishedStatus", "detail", stationId] as const,
  stationPublishedStatusOverview: (input: unknown = {}) => ["stationPublishedStatus", "overview", input] as const,
  captureSessionStatus: (stationId: string) => ["captureSessionStatus", stationId] as const,
  keyPool: ["keyPool"] as const,
  modelBasePrices: ["modelBasePrices"] as const,
  modelPriceSyncState: ["modelPriceSyncState"] as const,
  balanceSnapshots: ["balanceSnapshots"] as const,
  channelMonitoring: ["channelMonitoring"] as const,
  pricing: ["pricing"] as const,
  pricingGroupMonitorStatus: (input: PricingGroupMonitorStatusInput) =>
    ["pricingGroupMonitorStatus", input.schemaVersion, input.groupRefsHash, input.groups] as const,
  pricingGroupMonitorStatusPrefix: ["pricingGroupMonitorStatus"] as const,
  channelStatus: ["channelStatus"] as const,
  channelMonitorExecutions: ["channelMonitorExecutions"] as const,
  channelMonitorExecution: (executionId: string) => ["channelMonitorExecution", executionId] as const,
  channelMonitorAttempts: ["channelMonitorAttempts"] as const,
  monitoringCapabilities: ["monitoringCapabilities"] as const,
  alertingWorkspace: ["alertingWorkspace"] as const,
  alertingCurrentPrefix: ["alertingCurrent"] as const,
  alertingActivityPrefix: ["alertingActivity"] as const,
  alertingCurrent: (input: unknown = {}) => ["alertingCurrent", input] as const,
  alertingActivity: (input: unknown = {}) => ["alertingActivity", input] as const,
  alertingOccurrences: (input: unknown) => ["alertingOccurrences", input] as const,
  alertingDeliveries: (input: unknown) => ["alertingDeliveries", input] as const,
  runtimeDiagnostics: (input: unknown) => ["runtimeDiagnostics", input] as const,
} as const;
