export const queryKeys = {
  settings: ["settings"] as const,
  proxyStatus: ["proxyStatus"] as const,
  requestLogs: ["requestLogs"] as const,
  stations: ["stations"] as const,
  stationAssets: ["stationAssets"] as const,
  stationAssetsForStations: (stationIds: readonly string[]) =>
    ["stationAssets", "stations", stationIds] as const,
  stationAsset: (stationId: string) => ["stationAssets", stationId] as const,
  collectorSnapshots: (stationId: string) => ["collectorSnapshots", stationId] as const,
  collectorRuns: (stationId: string) => ["collectorRuns", stationId] as const,
  captureSessionStatus: (stationId: string) => ["captureSessionStatus", stationId] as const,
  keyPool: ["keyPool"] as const,
  modelBasePrices: ["modelBasePrices"] as const,
  balanceSnapshots: ["balanceSnapshots"] as const,
  changeEvents: ["changeEvents"] as const,
  localRoutingWorkspace: ["localRoutingWorkspace"] as const,
  channelMonitoring: ["channelMonitoring"] as const,
  pricing: ["pricing"] as const,
  channelStatus: ["channelStatus"] as const,
} as const;
