// @generated by repository IPC generator. Do not edit.
// generator version: 1
// IPC contract version: 1
// canonical hash: 3115c408311fefdac9c86297e2294c712b6cab5e618903fed6c7fb9cd386baf8

export type RuntimeCapability =
  | "runtime_contract"
  | "data_recovery"
  | "settings"
  | "stations"
  | "station_keys"
  | "collectors"
  | "routing"
  | "proxy"
  | "channel_monitoring"
  | "pricing"
  | "change_events"
  | "capture"
  | "typed_streaming";

export type RuntimeContractInfo = {
  appVersion: string;
  ipcContractVersion: number;
  bindingHash: string;
  capabilities: RuntimeCapability[];
};

export const IPC_CONTRACT_VERSION = 1 as const;
export const IPC_BINDING_HASH = "3115c408311fefdac9c86297e2294c712b6cab5e618903fed6c7fb9cd386baf8" as const;
