// @generated by repository IPC generator. Do not edit.
// generator version: 1
// IPC contract version: 1
// canonical hash: 288f1b11d724e61a5ade2ab87f8268cf4ce440c2995ae7f1caf346d88efbd7c6

export type RuntimeCapability =
  | "runtime_contract"
  | "data_recovery"
  | "settings"
  | "stations"
  | "station_keys"
  | "collectors"
  | "routing"
  | "proxy"
  | "channel_monitoring"
  | "pricing"
  | "change_events"
  | "capture"
  | "typed_streaming";

export type RuntimeContractInfo = {
  appVersion: string;
  ipcContractVersion: number;
  bindingHash: string;
  capabilities: RuntimeCapability[];
};

export const IPC_CONTRACT_VERSION = 1 as const;
export const IPC_BINDING_HASH = "288f1b11d724e61a5ade2ab87f8268cf4ce440c2995ae7f1caf346d88efbd7c6" as const;
