// @generated by repository IPC generator. Do not edit.
// generator version: 1
// IPC contract version: 1
// canonical hash: bea280d6bd1e1fcd9bec06c6222587917affd0a38b66817a479d475b51eeb0fe

export type RuntimeCapability =
  | "runtime_contract"
  | "data_recovery"
  | "settings"
  | "stations"
  | "station_keys"
  | "collectors"
  | "routing"
  | "proxy"
  | "channel_monitoring"
  | "pricing"
  | "alerting"
  | "capture"
  | "typed_streaming";

export type RuntimeContractInfo = {
  appVersion: string;
  ipcContractVersion: number;
  bindingHash: string;
  capabilities: RuntimeCapability[];
};

export const IPC_CONTRACT_VERSION = 1 as const;
export const IPC_BINDING_HASH = "bea280d6bd1e1fcd9bec06c6222587917affd0a38b66817a479d475b51eeb0fe" as const;
