// @generated by repository IPC generator. Do not edit.
// generator version: 1
// IPC contract version: 1
// canonical hash: 137b464c50e08f1bd357b3bd3d00b03d4c9ce1ae35d47819bcfbca8214977ff8

import { invoke, invokeNonIdempotent } from "@/lib/bridge/transport";

export type ChangeSeverityDto = "critical" | "warning" | "info";
export type ChangeEventStatusDto = "unread" | "read" | "dismissed" | "resolved";

export type ChangeEventIdInputDto = { id: string };
export type ChangeEventIdsInputDto = { ids: string[] };
export type ChangeLogStationIdInputDto = { stationId: string };

export type UpsertChangeEventInputDto = {
  severity: ChangeSeverityDto;
  eventType: string;
  title: string;
  message: string;
  objectType: string;
  objectId: string | null;
  stationId: string | null;
  stationKeyId: string | null;
  pricingRuleId: string | null;
  requestLogId: string | null;
  oldValueJson: string | null;
  newValueJson: string | null;
  impactJson: string | null;
  dedupeKey: string;
  source: string;
};

export type ChangeEventDto = {
  id: string; severity: ChangeSeverityDto; eventType: string; status: ChangeEventStatusDto; title: string; message: string;
  objectType: string; objectId: string | null; stationId: string | null; stationName: string | null;
  stationKeyId: string | null; pricingRuleId: string | null; requestLogId: string | null;
  oldValueJson: string | null; newValueJson: string | null; impactJson: string | null;
  dedupeKey: string; source: string; detectedAt: string; resolvedAt: string | null;
  createdAt: string; updatedAt: string;
};

export type RequestLogDto = {
  id: string; requestId: string | null; startedAt: string; finishedAt: string | null;
  durationMs: number | null; method: string; path: string; model: string | null; stream: boolean;
  status: string; lifecycleStatus: string | null; stationKeyId: string | null; stationId: string | null;
  upstreamBaseUrl: string | null; fallbackCount: number; errorMessage: string | null;
  routePolicy: string | null; routeReason: string | null; rejectedCandidatesJson: string | null;
  bodyBytes: number | null; attemptCount: number | null; routeWaitMs: number | null;
  upstreamHeadersMs: number | null; failureSource: string | null; attemptsJson: string | null;
  completionSource: string | null; promptTokens: number | null; completionTokens: number | null;
  totalTokens: number | null; cacheCreationTokens: number | null; cacheReadTokens: number | null;
  reasoningEffort: string | null; firstTokenMs: number | null; billingMode: string | null;
  estimatedInputCost: number | null; estimatedOutputCost: number | null; estimatedTotalCost: number | null;
  baseInputCost: number | null; baseOutputCost: number | null; baseFixedCost: number | null;
  baseTotalCost: number | null; costCurrency: string | null; pricingRuleId: string | null;
  pricingSource: string | null; costStatus: string | null; groupBindingId: string | null;
  normalizationStatus: string | null; balanceScope: string | null; economicContextJson: string | null;
  createdAt: string;
};


export type ChannelMonitorTargetTypeInputDto = "station_key" | "station";
export type ChannelMonitorMutationIdInputDto = { id: string };

export type CreateChannelMonitorInputDto = {
  name: string; targetType: ChannelMonitorTargetTypeInputDto; stationId: string;
  stationKeyId: string | null; templateId: string; enabled: boolean; intervalSeconds: number;
  jitterSeconds: number; timeoutSeconds: number; maxConcurrency: number;
  consecutiveFailureThreshold: number; fallbackModels: string[]; note: string | null;
};

export type UpdateChannelMonitorInputDto = CreateChannelMonitorInputDto & { id: string };

export type CreateChannelMonitorTemplateInputDto = {
  name: string; endpointKind: string; method: string; path: string;
  requestBodyJson: string; enabled: boolean; note: string | null;
};

export type UpdateChannelMonitorTemplateInputDto = CreateChannelMonitorTemplateInputDto & { id: string };


export type StationKeyHealthDto = {
  stationKeyId: string; lastSuccessAt: string | null; lastFailureAt: string | null;
  consecutiveFailures: number; successCount: number; failureCount: number;
  avgLatencyMs: number | null; lastErrorSummary: string | null; cooldownUntil: string | null;
  updatedAt: string;
};

export type ChannelStatusWorkspaceDto = {
  keyPoolItems: KeyPoolItemDto[];
  requestLogs: RequestLogDto[];
  stationKeyHealth: StationKeyHealthDto[];
  channelStatusSummaries: ChannelStatusSummaryDto[];
};


export type ChannelMonitorIdInputDto = { monitorId: string };
export type ChannelMonitorSummaryInputDto = { runSince: string | null; runLimit: number | null };
export type ChannelMonitorTargetTypeDto = "station_key" | "station";
export type ChannelMonitorRunStatusDto = "success" | "warning" | "failed" | "skipped";

export type ChannelMonitorDto = {
  id: string; name: string; targetType: ChannelMonitorTargetTypeDto; stationId: string;
  stationKeyId: string | null; templateId: string; enabled: boolean; intervalSeconds: number;
  jitterSeconds: number; timeoutSeconds: number; maxConcurrency: number;
  consecutiveFailureThreshold: number; fallbackModels: string[]; note: string | null;
  createdAt: string; updatedAt: string;
};

export type ChannelMonitorRunDto = {
  id: string; monitorId: string; templateId: string; stationId: string; stationKeyId: string | null;
  status: ChannelMonitorRunStatusDto; startedAt: string; finishedAt: string | null;
  durationMs: number | null; httpStatus: number | null; latencyMs: number | null;
  responseModel: string | null; fallbackModel: string | null; errorMessage: string | null; createdAt: string;
};

export type ChannelMonitorRequestTemplateDto = {
  id: string; name: string; endpointKind: string; method: string; path: string;
  requestBodyJson: string; enabled: boolean; builtIn: boolean; note: string | null;
  createdAt: string; updatedAt: string;
};

export type ChannelMonitorSummaryDto = {
  monitor: ChannelMonitorDto; recentRuns: ChannelMonitorRunDto[]; runsLoadStatus: "ok" | "failed";
  latestRun: ChannelMonitorRunDto | null;
};

export type ChannelStatusTimelinePointDto = {
  status: ChannelMonitorRunStatusDto; latencyMs: number | null; endpointPingMs: number | null; checkedAt: string;
};

export type ChannelStatusWindowSummaryDto = {
  window: "recent" | "24h" | "7d"; totalCount: number; successCount: number; failureCount: number;
  warningCount: number; availabilityPercent: number | null; avgLatencyMs: number | null;
  avgEndpointPingMs: number | null; lastCheckedAt: string | null;
  latestStatus: ChannelMonitorRunStatusDto | null; latestErrorMessage: string | null;
  timeline: ChannelStatusTimelinePointDto[];
};

export type ChannelStatusSummaryDto = {
  monitor: ChannelMonitorDto; recent: ChannelStatusWindowSummaryDto;
  last24h: ChannelStatusWindowSummaryDto; last7d: ChannelStatusWindowSummaryDto;
};


export type CollectorStationIdInputDto = { stationId: string };
export type BalanceScopeDto = "station" | "station_key";
export type BalanceStatusDto = "unknown" | "normal" | "low" | "depleted";
export type BindingKindDto = "station_group" | "key_binding";
export type BindingStatusDto = "available" | "bound" | "missing" | "disabled" | "manual_legacy";
export type StationGroupCategoryDto = "gpt" | "claude" | "gemini" | "grok" | "image_generation" | "embedding" | "rerank" | "unknown";

export type UpsertBalanceSnapshotInputDto = {
  id: string | null; stationId: string; stationKeyId: string | null; scope: BalanceScopeDto;
  value: number | null; currency: string; creditUnit: string | null; usedValue: number | null;
  totalValue: number | null; todayRequestCount: number | null; totalRequestCount: number | null;
  todayConsumption: number | null; totalConsumption: number | null; todayBaseConsumption: number | null;
  totalBaseConsumption: number | null; todayTokenCount: number | null; totalTokenCount: number | null;
  todayInputTokenCount: number | null; todayOutputTokenCount: number | null;
  totalInputTokenCount: number | null; totalOutputTokenCount: number | null;
  accountConcurrencyLimit: number | null; lowBalanceThreshold: number | null;
  status: BalanceStatusDto; source: string; confidence: number; collectedAt: string | null;
};

export type BalanceSnapshotDto = Omit<UpsertBalanceSnapshotInputDto, "id" | "scope" | "status"> & {
  id: string; scope: string; status: string; createdAt: string; updatedAt: string;
};

export type UpsertStationGroupBindingInputDto = {
  stationId: string; stationKeyId: string | null; bindingKind: BindingKindDto;
  parentGroupBindingId: string | null; groupKeyHash: string; groupIdHash: string | null;
  groupName: string; bindingStatus: BindingStatusDto; defaultRateMultiplier: number | null;
  userRateMultiplier: number | null; effectiveRateMultiplier: number | null;
  inferredGroupCategory: StationGroupCategoryDto | null; groupCategoryOverride: StationGroupCategoryDto | null;
  rateSource: string | null; confidence: number; lastSeenAt: string | null;
  rawJsonRedacted: Record<string, unknown> | null;
};

export type StationGroupBindingDto = Omit<UpsertStationGroupBindingInputDto, "bindingKind" | "bindingStatus" | "inferredGroupCategory" | "groupCategoryOverride"> & {
  id: string; bindingKind: string; bindingStatus: string; inferredGroupCategory: string | null;
  groupCategoryOverride: string | null; lastCheckedAt: string | null; lastRateChangedAt: string | null;
  createdAt: string; updatedAt: string;
};

export type StationGroupOptionDto = {
  value: string; groupBindingId: string | null; groupIdHash: string | null; groupName: string;
  rateMultiplier: number | null; inferredGroupCategory: string | null;
  groupCategoryOverride: string | null; effectiveGroupCategory: string;
  rateSource: string | null; selectableForRemoteKey: boolean;
};

export type GroupRateRecordDto = {
  id: string; stationId: string; stationKeyId: string | null; groupBindingId: string | null;
  bindingKind: string; groupKeyHash: string; groupName: string;
  defaultRateMultiplier: number | null; userRateMultiplier: number | null;
  effectiveRateMultiplier: number | null; inferredGroupCategory: string | null;
  source: string; confidence: number; rawJsonRedacted: Record<string, unknown> | null;
  checkedAt: string; createdAt: string;
};

export type CollectorRunDto = {
  id: string; stationId: string; endpointRevision: number; parentRunId: string | null;
  adapter: string; taskType: string; status: string; startedAt: string; finishedAt: string | null;
  durationMs: number | null; endpointCount: number; successCount: number; failureCount: number;
  manualActionRequired: boolean; errorCode: string | null; errorMessage: string | null;
  snapshotId: string | null; createdAt: string;
};

export type CollectorSnapshotDto = {
  id: string; stationId: string; endpointRevision: number; source: string; status: string;
  fetchedAt: string; summaryJson: Record<string, unknown>; normalizedJson: Record<string, unknown>;
  rawJsonRedacted: Record<string, unknown> | null; errorMessage: string | null; createdAt: string;
};


export type EmptyInputDto = Record<string, never>;

export type RoutingGroupFilter =
  | "all_groups"
  | "ungrouped_only"
  | { group_binding_id: string }
  | { group_id_hash: string }
  | { group_type: "gpt" | "claude" | "gemini" | "grok" | "image_generation" };

export type SchedulerAdvancedSettingsDto = {
  topK: number;
  multiplier: number;
  priority: number;
  load: number;
  queue: number;
  errorRate: number;
  ttft: number;
  quotaHeadroom: number;
  previousResponse: number;
  sessionSticky: number;
  multiplierMinConfidence: number;
  stickyWeighted: boolean;
  stickyEscape: boolean;
  stickyEscapeTtftMs: number;
  stickyEscapeErrorRate: number;
  stickySessionTtlSeconds: number;
  stickyResponseTtlSeconds: number;
  stickyMaxWaiting: number;
  stickyWaitTimeoutSeconds: number;
  fallbackMaxWaiting: number;
  fallbackWaitTimeoutSeconds: number;
};

export type RoutingStrategyInput =
  | "automatic_balanced"
  | "priority_fallback"
  | "stable_first"
  | "backup_only"
  | "cheap_first"
  | "cost_stable_first";

export type CollectorProxyModeInput = "direct" | "system" | "manual";

export type UpdateSettingsInputDto = {
  localProxyPort: number;
  defaultRoutingStrategy: RoutingStrategyInput;
  collectorProxyMode: CollectorProxyModeInput;
  collectorProxyUrl: string | null;
  maxRateMultiplier: number | null;
  defaultRoutingGroupFilter?: RoutingGroupFilter;
  schedulerAdvancedSettings?: SchedulerAdvancedSettingsDto | null;
  lowBalanceThresholdCny: number;
  collectorIntervalMinutes: number;
  balanceIntervalMinutes: number;
  groupRateIntervalMinutes: number;
  modelListIntervalMinutes: number;
  pricingRefreshIntervalMinutes: number;
  collectorTimeoutSeconds: number;
  collectorMaxConcurrency: number;
  allowDepletedFallback: boolean;
  developerModeEnabled: boolean;
  trayBehavior?: "close_to_tray" | "minimize_to_tray" | "disabled";
};

export type SettingsDto = {
  localProxyPort: number;
  localProxyStartOnLaunch: boolean;
  localKeyMasked: string;
  defaultRoutingStrategy: string;
  collectorProxyMode: string;
  collectorProxyUrl: string | null;
  maxRateMultiplier: number | null;
  defaultRoutingGroupFilter: RoutingGroupFilter;
  schedulerAdvancedSettings: SchedulerAdvancedSettingsDto;
  lowBalanceThresholdCny: number;
  collectorIntervalMinutes: number;
  balanceIntervalMinutes: number;
  groupRateIntervalMinutes: number;
  modelListIntervalMinutes: number;
  pricingRefreshIntervalMinutes: number;
  collectorTimeoutSeconds: number;
  collectorMaxConcurrency: number;
  allowDepletedFallback: boolean;
  developerModeEnabled: boolean;
  trayBehavior: string;
  dataDir: string;
  pendingDataDir: string | null;
  dataDirChangeRequiresRestart: boolean;
};

export type StationIdInputDto = { stationId: string };
export type StationKeyIdInputDto = { id: string };
export type RemoteStationKeyInputDto = { remoteKeyId: string; stationId: string };
export type ReorderKeyPoolInputDto = { keyIds: string[] };
export type ReorderStationKeysInputDto = { stationId: string; keyIds: string[] };

export type StationKeyStatusInput = "unchecked" | "healthy" | "warning" | "error" | "disabled";

export type CreateStationKeyInputDto = {
  stationId: string;
  name: string;
  apiKey: string;
  enabled: boolean;
  priority?: number | null;
  maxConcurrency?: number | null;
  loadFactor?: number | null;
  schedulable?: boolean | null;
  groupName: string | null;
  tierLabel: string | null;
  groupBindingId?: string | null;
  groupIdHash?: string | null;
  rateMultiplier?: number | null;
  manualRateMultiplier?: number | null;
  rateSource?: string | null;
  balanceScope?: string | null;
  note: string | null;
};

export type UpdateStationKeyInputDto = Omit<CreateStationKeyInputDto, "apiKey" | "priority" | "maxConcurrency" | "schedulable"> & {
  id: string;
  apiKey: string | null;
  priority: number;
  maxConcurrency: number;
  schedulable: boolean;
  status: StationKeyStatusInput;
};

export type CreateRemoteStationKeyInputDto = {
  stationId: string;
  name: string;
  groupBindingId: string | null;
  groupIdHash: string | null;
  groupName: string | null;
};

export type BindRemoteStationKeyInputDto = { remoteKeyId: string; stationKeyId: string };
export type UpdateStationKeyGroupBindingInputDto = { stationKeyId: string; groupBindingId: string };
export type UpdateStationCredentialsInputDto = {
  stationId: string;
  loginUsername: string | null;
  loginPassword: string | null;
  rememberPassword: boolean;
};
export type UpdateStationSessionInputDto = {
  stationId: string;
  accessToken: string | null;
  refreshToken: string | null;
  cookie: string | null;
  newapiUserId: string | null;
  tokenExpiresAt: string | null;
};

export type UpdateStationKeyCapabilitiesInputDto = {
  stationKeyId: string;
  supportsChatCompletions: boolean;
  supportsResponses: boolean;
  supportsEmbeddings: boolean;
  supportsStream: boolean;
  supportsTools: boolean;
  supportsVision: boolean;
  supportsReasoning: boolean;
  modelAllowlist: string[];
  modelBlocklist: string[];
  preferredModels: string[];
  onlyUseAsBackup: boolean;
  routingTags: string[];
};

export type SaveStationKeyGroupSelectionDto =
  | { kind: "keep"; groupBindingId?: null; groupIdHash?: null; groupName?: null }
  | { kind: "clear"; groupBindingId?: null; groupIdHash?: null; groupName?: null }
  | { kind: "set"; groupBindingId: string; groupIdHash?: string | null; groupName?: string | null };

export type SaveStationKeyWithDefaultsInputDto = {
  mode: "create" | "update";
  id?: string | null;
  stationId: string;
  name: string;
  apiKey?: string | null;
  enabled: boolean;
  schedulable?: boolean | null;
  priority?: number | null;
  tierLabel?: string | null;
  balanceScope?: string | null;
  status?: StationKeyStatusInput | null;
  note?: string | null;
  groupSelection: SaveStationKeyGroupSelectionDto;
  capabilities?: UpdateStationKeyCapabilitiesInputDto | null;
};

export type StationKeyDto = {
  id: string;
  stationId: string;
  name: string;
  apiKeyMasked: string;
  apiKeyPresent: boolean;
  enabled: boolean;
  priority: number;
  maxConcurrency: number;
  loadFactor: number | null;
  schedulable: boolean;
  groupName: string | null;
  tierLabel: string | null;
  groupBindingId: string | null;
  groupIdHash: string | null;
  rateMultiplier: number | null;
  manualRateMultiplier: number | null;
  manualRateUpdatedAt: string | null;
  rateSource: string | null;
  rateCollectedAt: string | null;
  balanceScope: string | null;
  status: StationKeyStatusInput;
  lastCheckedAt: string | null;
  lastUsedAt: string | null;
  note: string | null;
  createdAt: string;
  updatedAt: string;
};

export type KeyPoolItemDto = StationKeyDto & {
  stationName: string;
  stationType: string;
  stationApiBaseUrl: string;
  stationEndpointRevision: number;
  stationUpstreamApiFormat: "auto" | "openai_chat_completions" | "openai_responses" | "custom_openai_compatible";
  capabilitySummary: string[];
  modelScopeSummary: string;
  onlyUseAsBackup: boolean;
  cooldownUntil: string | null;
  successRate: number | null;
  avgLatencyMs: number | null;
  consecutiveFailures: number;
  lastErrorSummary: string | null;
  endpointPingStatus: "unchecked" | "success" | "failed";
  endpointPingMs: number | null;
  endpointPingCheckedAt: string | null;
  endpointPingError: string | null;
};

export type RemoteKeyCapabilityDto = {
  stationId: string;
  stationType: string;
  canListRemoteKeys: boolean;
  canCreateRemoteKey: boolean;
  canReadGroups: boolean;
  requiresManualSession: boolean;
  unsupportedReason: string | null;
};

export type RemoteStationKeyDto = {
  id: string;
  stationId: string;
  remoteKeyIdHash: string | null;
  remoteKeyName: string | null;
  apiKeyMasked: string | null;
  apiKeyFingerprint: string | null;
  groupIdHash: string | null;
  groupName: string | null;
  tierLabel: string | null;
  rateMultiplier: number | null;
  rateSource: string | null;
  createdAt: string | null;
  lastUsedAt: string | null;
  rawSource: string;
  matchStatus: "matched" | "possible" | "unbound";
  matchedStationKeyId: string | null;
  matchConfidence: number;
  collectedAt: string;
};

export type RemoteKeyScanResultDto = {
  stationId: string;
  capability: RemoteKeyCapabilityDto;
  keys: RemoteStationKeyDto[];
  syncedStationKeyIds: string[];
  message: string;
};

export type CreateRemoteStationKeyResultDto = {
  remoteKey: RemoteStationKeyDto;
  stationKey: StationKeyDto;
  fullKeyOnce: string | null;
  message: string;
};
export type CreateLocalStationKeyFromRemoteResultDto = {
  remoteKey: RemoteStationKeyDto;
  stationKey: StationKeyDto;
  message: string;
};

export type StationCredentialsDto = {
  stationId: string;
  loginUsername: string | null;
  passwordPresent: boolean;
  accessTokenPresent: boolean;
  refreshTokenPresent: boolean;
  cookiePresent: boolean;
  rememberPassword: boolean;
  loginStatus: string;
  loginError: string | null;
  lastLoginAt: string | null;
  sessionStatus: string;
  sessionExpiresAt: string | null;
  newapiUserId: string | null;
  tokenExpiresAt: string | null;
  tokenRefreshedAt: string | null;
  sessionSource: string;
  updatedAt: string | null;
};

export type SaveStationKeyWithDefaultsResultDto = {
  stationKey: StationKeyDto;
  capabilities: UpdateStationKeyCapabilitiesInputDto & { updatedAt: string };
  message: string;
};


export type StationTypeInput = "sub2api" | "newapi" | "openai-compatible" | "custom";

export type StationProxyModeInput = "inherit" | "direct" | "system" | "manual";

export type CreateStationInputDto = {
  name: string;
  stationType: StationTypeInput;
  websiteUrl: string;
  apiBaseUrl: string;
  apiKey: string;
  collectorProxyMode: StationProxyModeInput;
  collectorProxyUrl: string | null;
  enabled: boolean;
  creditPerCny: number;
  lowBalanceThresholdCny: number | null;
  collectionIntervalMinutes: number;
  note: string | null;
};

export type UpdateStationInputDto = Omit<CreateStationInputDto, "apiKey"> & {
  id: string;
  apiKey: string | null;
};

export type DeleteStationInputDto = { id: string };

export type ReorderStationsInputDto = { stationIds: string[] };

export type StationDto = {
  id: string;
  name: string;
  stationType: string;
  websiteUrl: string;
  apiBaseUrl: string;
  endpointRevision: number;
  collectorProxyMode: string;
  collectorProxyUrl: string | null;
  apiKeyMasked: string;
  apiKeyPresent: boolean;
  keyCount: number;
  enabled: boolean;
  priority: number;
  creditPerCny: number;
  balanceRaw: number | null;
  balanceCny: number | null;
  lowBalanceThresholdCny: number | null;
  collectionIntervalMinutes: number;
  status: string;
  latencyMs: number | null;
  lastCheckedAt: string | null;
  lastPricingFetchedAt: string | null;
  note: string | null;
  createdAt: string;
  updatedAt: string;
};

export type RuntimeCapability =
  | "runtime_contract"
  | "data_recovery"
  | "settings"
  | "stations"
  | "station_keys"
  | "collectors"
  | "routing"
  | "proxy"
  | "channel_monitoring"
  | "pricing"
  | "change_events"
  | "capture"
  | "typed_streaming";

export type RuntimeContractInfo = {
  appVersion: string;
  ipcContractVersion: number;
  bindingHash: string;
  capabilities: RuntimeCapability[];
};

export type CommandErrorCode =
  | "invalid_input"
  | "not_found"
  | "conflict"
  | "permission_denied"
  | "runtime_unavailable"
  | "data_store_unavailable"
  | "external_unavailable"
  | "timeout"
  | "overloaded"
  | "unsupported"
  | "internal";

export type PublicFieldError = {
  field: string;
  code: string;
  message: string;
};

export type PublicErrorDetails =
  | { kind: "validation"; fields: PublicFieldError[] }
  | { kind: "conflict"; resource: string; currentRevision: string | null }
  | { kind: "retry"; retryAfterMs: number | null }
  | { kind: "external"; provider: string | null; upstreamStatus: number | null };

export type CommandError = {
  code: CommandErrorCode;
  message: string;
  retryable: boolean;
  details: PublicErrorDetails | null;
  correlationId: string | null;
};

export type IpcCommand =
  | "activate_data_store_candidate"
  | "app_status"
  | "bind_remote_station_key"
  | "choose_data_dir"
  | "cleanup_before_update"
  | "clear_capture_session"
  | "clear_change_events"
  | "clear_request_logs"
  | "clear_station_credentials"
  | "close_capture_session"
  | "collect_station_info"
  | "collect_station_task"
  | "collect_sub2api_station"
  | "create_channel_monitor"
  | "create_channel_monitor_template"
  | "create_local_station_key_from_remote"
  | "create_new_data_store"
  | "create_remote_station_key"
  | "create_station"
  | "create_station_key"
  | "delete_channel_monitor"
  | "delete_channel_monitor_template"
  | "delete_model_alias"
  | "delete_pricing_rule"
  | "delete_station"
  | "delete_station_key"
  | "detect_station_info"
  | "detect_sub2api_station"
  | "dismiss_change_event"
  | "duplicate_channel_monitor_template"
  | "export_data_store_diagnostic"
  | "finish_capture_session"
  | "finish_web_authorization_session"
  | "get_capture_session_status"
  | "get_data_store_startup_state"
  | "get_latest_collector_snapshot"
  | "get_local_access_key"
  | "get_proxy_status"
  | "get_remote_key_capability"
  | "get_runtime_contract_info"
  | "get_settings"
  | "get_station_credentials"
  | "get_station_key_capabilities"
  | "get_station_key_health"
  | "import_relay_pool_to_ccswitch"
  | "inspect_latest_update_manifest"
  | "list_balance_snapshots"
  | "list_balance_snapshots_for_station"
  | "list_change_events"
  | "list_change_events_for_station"
  | "list_channel_monitor_runs"
  | "list_channel_monitor_summaries"
  | "list_channel_monitor_templates"
  | "list_channel_monitors"
  | "list_channel_status_summaries"
  | "list_collector_runs"
  | "list_collector_snapshots"
  | "list_current_station_balance_snapshots"
  | "list_group_rate_records"
  | "list_key_pool_items"
  | "list_model_aliases"
  | "list_model_base_prices"
  | "list_pricing_rules"
  | "list_remote_station_keys"
  | "list_request_logs"
  | "list_station_endpoint_health"
  | "list_station_group_bindings"
  | "list_station_group_options"
  | "list_station_key_health"
  | "list_station_keys"
  | "list_stations"
  | "load_channel_status_workspace"
  | "load_local_routing_workspace"
  | "load_pricing_comparison_workspace"
  | "locate_data_store_candidate"
  | "mark_change_event_read"
  | "mark_change_events_read"
  | "open_data_store_backup_dir"
  | "open_external_url"
  | "ping_station_endpoint"
  | "prepare_local_proxy_for_update"
  | "record_capture_event"
  | "refresh_data_store_candidates"
  | "reorder_key_pool"
  | "reorder_local_routing_keys"
  | "reorder_station_keys"
  | "reorder_stations"
  | "reset_data_dir"
  | "reset_model_base_prices_to_builtins"
  | "resolve_change_event"
  | "resolve_station_key_pricing_context"
  | "restart_local_proxy"
  | "run_channel_monitor_now"
  | "save_station_key_with_defaults"
  | "scan_remote_station_keys"
  | "simulate_route"
  | "start_capture_session"
  | "start_local_proxy"
  | "stop_local_proxy"
  | "test_station_key_connectivity"
  | "test_station_login"
  | "test_station_login_input"
  | "unbind_remote_station_key"
  | "update_channel_monitor"
  | "update_channel_monitor_template"
  | "update_local_access_key"
  | "update_settings"
  | "update_station"
  | "update_station_credentials"
  | "update_station_key"
  | "update_station_key_capabilities"
  | "update_station_key_group_binding"
  | "update_station_session"
  | "updater_network_config"
  | "upsert_balance_snapshot"
  | "upsert_change_event"
  | "upsert_model_alias"
  | "upsert_model_base_price"
  | "upsert_pricing_rule"
  | "upsert_station_group_binding";

export const IPC_CONTRACT_VERSION = 1 as const;
export const IPC_BINDING_HASH = "137b464c50e08f1bd357b3bd3d00b03d4c9ce1ae35d47819bcfbca8214977ff8" as const;

export function invokeCommand<T>(command: IpcCommand, args?: Record<string, unknown>): Promise<T> {
  return invoke<T>(command, args);
}

export function getSettings(input: EmptyInputDto = {}): Promise<SettingsDto> {
  return invokeCommand<SettingsDto>("get_settings", { input });
}

export function listStations(input: EmptyInputDto = {}): Promise<StationDto[]> {
  return invokeCommand<StationDto[]>("list_stations", { input });
}

export function updateSettings(input: UpdateSettingsInputDto): Promise<SettingsDto> {
  return invokeCommand<SettingsDto>("update_settings", { input });
}

export function createStation(input: CreateStationInputDto): Promise<StationDto> {
  return invokeNonIdempotent<StationDto>("create_station", { input });
}

export function updateStation(input: UpdateStationInputDto): Promise<StationDto> {
  return invokeCommand<StationDto>("update_station", { input });
}

export function deleteStation(input: DeleteStationInputDto): Promise<void> {
  return invokeCommand<void>("delete_station", { input });
}

export function reorderStations(input: ReorderStationsInputDto): Promise<StationDto[]> {
  return invokeCommand<StationDto[]>("reorder_stations", { input });
}

export function listStationKeys(input: StationIdInputDto): Promise<StationKeyDto[]> {
  return invokeCommand<StationKeyDto[]>("list_station_keys", { input });
}

export function createStationKey(input: CreateStationKeyInputDto): Promise<StationKeyDto> {
  return invokeNonIdempotent<StationKeyDto>("create_station_key", { input });
}

export function updateStationKey(input: UpdateStationKeyInputDto): Promise<StationKeyDto> {
  return invokeCommand<StationKeyDto>("update_station_key", { input });
}

export function saveStationKeyWithDefaults(input: SaveStationKeyWithDefaultsInputDto): Promise<SaveStationKeyWithDefaultsResultDto> {
  return invokeNonIdempotent<SaveStationKeyWithDefaultsResultDto>("save_station_key_with_defaults", { input });
}

export function updateStationKeyGroupBinding(input: UpdateStationKeyGroupBindingInputDto): Promise<StationKeyDto> {
  return invokeCommand<StationKeyDto>("update_station_key_group_binding", { input });
}

export function deleteStationKey(input: StationKeyIdInputDto): Promise<void> {
  return invokeCommand<void>("delete_station_key", { input });
}

export function reorderStationKeys(input: ReorderStationKeysInputDto): Promise<StationKeyDto[]> {
  return invokeCommand<StationKeyDto[]>("reorder_station_keys", { input });
}

export function getRemoteKeyCapability(input: StationIdInputDto): Promise<RemoteKeyCapabilityDto> {
  return invokeCommand<RemoteKeyCapabilityDto>("get_remote_key_capability", { input });
}

export function listRemoteStationKeys(input: StationIdInputDto): Promise<RemoteStationKeyDto[]> {
  return invokeCommand<RemoteStationKeyDto[]>("list_remote_station_keys", { input });
}

export function scanRemoteStationKeys(input: StationIdInputDto): Promise<RemoteKeyScanResultDto> {
  return invokeCommand<RemoteKeyScanResultDto>("scan_remote_station_keys", { input });
}

export function createRemoteStationKey(input: CreateRemoteStationKeyInputDto): Promise<CreateRemoteStationKeyResultDto> {
  return invokeNonIdempotent<CreateRemoteStationKeyResultDto>("create_remote_station_key", { input });
}

export function createLocalStationKeyFromRemote(input: RemoteStationKeyInputDto): Promise<CreateLocalStationKeyFromRemoteResultDto> {
  return invokeNonIdempotent<CreateLocalStationKeyFromRemoteResultDto>("create_local_station_key_from_remote", { input });
}

export function bindRemoteStationKey(input: BindRemoteStationKeyInputDto): Promise<RemoteStationKeyDto[]> {
  return invokeCommand<RemoteStationKeyDto[]>("bind_remote_station_key", { input });
}

export function unbindRemoteStationKey(input: RemoteStationKeyInputDto): Promise<RemoteStationKeyDto[]> {
  return invokeCommand<RemoteStationKeyDto[]>("unbind_remote_station_key", { input });
}

export function listKeyPoolItems(input: EmptyInputDto = {}): Promise<KeyPoolItemDto[]> {
  return invokeCommand<KeyPoolItemDto[]>("list_key_pool_items", { input });
}

export function reorderKeyPool(input: ReorderKeyPoolInputDto): Promise<KeyPoolItemDto[]> {
  return invokeCommand<KeyPoolItemDto[]>("reorder_key_pool", { input });
}

export function getStationCredentials(input: StationIdInputDto): Promise<StationCredentialsDto> {
  return invokeCommand<StationCredentialsDto>("get_station_credentials", { input });
}

export function updateStationCredentials(input: UpdateStationCredentialsInputDto): Promise<StationCredentialsDto> {
  return invokeCommand<StationCredentialsDto>("update_station_credentials", { input });
}

export function updateStationSession(input: UpdateStationSessionInputDto): Promise<StationCredentialsDto> {
  return invokeCommand<StationCredentialsDto>("update_station_session", { input });
}

export function clearStationCredentials(input: StationIdInputDto): Promise<StationCredentialsDto> {
  return invokeCommand<StationCredentialsDto>("clear_station_credentials", { input });
}

export function listRequestLogs(input: EmptyInputDto = {}): Promise<RequestLogDto[]> {
  return invokeCommand<RequestLogDto[]>("list_request_logs", { input });
}

export function clearRequestLogs(input: EmptyInputDto = {}): Promise<void> {
  return invokeCommand<void>("clear_request_logs", { input });
}

export function listChangeEvents(input: EmptyInputDto = {}): Promise<ChangeEventDto[]> {
  return invokeCommand<ChangeEventDto[]>("list_change_events", { input });
}

export function clearChangeEvents(input: EmptyInputDto = {}): Promise<void> {
  return invokeCommand<void>("clear_change_events", { input });
}

export function listChangeEventsForStation(input: ChangeLogStationIdInputDto): Promise<ChangeEventDto[]> {
  return invokeCommand<ChangeEventDto[]>("list_change_events_for_station", { input });
}

export function upsertChangeEvent(input: UpsertChangeEventInputDto): Promise<ChangeEventDto> {
  return invokeCommand<ChangeEventDto>("upsert_change_event", { input });
}

export function markChangeEventRead(input: ChangeEventIdInputDto): Promise<ChangeEventDto> {
  return invokeCommand<ChangeEventDto>("mark_change_event_read", { input });
}

export function markChangeEventsRead(input: ChangeEventIdsInputDto): Promise<ChangeEventDto[]> {
  return invokeCommand<ChangeEventDto[]>("mark_change_events_read", { input });
}

export function dismissChangeEvent(input: ChangeEventIdInputDto): Promise<ChangeEventDto> {
  return invokeCommand<ChangeEventDto>("dismiss_change_event", { input });
}

export function resolveChangeEvent(input: ChangeEventIdInputDto): Promise<ChangeEventDto> {
  return invokeCommand<ChangeEventDto>("resolve_change_event", { input });
}

export function listBalanceSnapshots(input: EmptyInputDto = {}): Promise<BalanceSnapshotDto[]> {
  return invokeCommand<BalanceSnapshotDto[]>("list_balance_snapshots", { input });
}

export function listCurrentStationBalanceSnapshots(input: EmptyInputDto = {}): Promise<BalanceSnapshotDto[]> {
  return invokeCommand<BalanceSnapshotDto[]>("list_current_station_balance_snapshots", { input });
}

export function listBalanceSnapshotsForStation(input: CollectorStationIdInputDto): Promise<BalanceSnapshotDto[]> {
  return invokeCommand<BalanceSnapshotDto[]>("list_balance_snapshots_for_station", { input });
}

export function upsertBalanceSnapshot(input: UpsertBalanceSnapshotInputDto): Promise<BalanceSnapshotDto> {
  return invokeCommand<BalanceSnapshotDto>("upsert_balance_snapshot", { input });
}

export function listStationGroupBindings(input: CollectorStationIdInputDto): Promise<StationGroupBindingDto[]> {
  return invokeCommand<StationGroupBindingDto[]>("list_station_group_bindings", { input });
}

export function listStationGroupOptions(input: CollectorStationIdInputDto): Promise<StationGroupOptionDto[]> {
  return invokeCommand<StationGroupOptionDto[]>("list_station_group_options", { input });
}

export function upsertStationGroupBinding(input: UpsertStationGroupBindingInputDto): Promise<StationGroupBindingDto> {
  return invokeCommand<StationGroupBindingDto>("upsert_station_group_binding", { input });
}

export function listGroupRateRecords(input: CollectorStationIdInputDto): Promise<GroupRateRecordDto[]> {
  return invokeCommand<GroupRateRecordDto[]>("list_group_rate_records", { input });
}

export function listCollectorRuns(input: CollectorStationIdInputDto): Promise<CollectorRunDto[]> {
  return invokeCommand<CollectorRunDto[]>("list_collector_runs", { input });
}

export function listCollectorSnapshots(input: CollectorStationIdInputDto): Promise<CollectorSnapshotDto[]> {
  return invokeCommand<CollectorSnapshotDto[]>("list_collector_snapshots", { input });
}

export function getLatestCollectorSnapshot(input: CollectorStationIdInputDto): Promise<CollectorSnapshotDto | null> {
  return invokeCommand<CollectorSnapshotDto | null>("get_latest_collector_snapshot", { input });
}

export function listChannelMonitors(input: EmptyInputDto = {}): Promise<ChannelMonitorDto[]> {
  return invokeCommand<ChannelMonitorDto[]>("list_channel_monitors", { input });
}

export function listChannelMonitorSummaries(input: ChannelMonitorSummaryInputDto): Promise<ChannelMonitorSummaryDto[]> {
  return invokeCommand<ChannelMonitorSummaryDto[]>("list_channel_monitor_summaries", { input });
}

export function listChannelStatusSummaries(input: EmptyInputDto = {}): Promise<ChannelStatusSummaryDto[]> {
  return invokeCommand<ChannelStatusSummaryDto[]>("list_channel_status_summaries", { input });
}

export function listChannelMonitorRuns(input: ChannelMonitorIdInputDto): Promise<ChannelMonitorRunDto[]> {
  return invokeCommand<ChannelMonitorRunDto[]>("list_channel_monitor_runs", { input });
}

export function listChannelMonitorTemplates(input: EmptyInputDto = {}): Promise<ChannelMonitorRequestTemplateDto[]> {
  return invokeCommand<ChannelMonitorRequestTemplateDto[]>("list_channel_monitor_templates", { input });
}

export function createChannelMonitor(input: CreateChannelMonitorInputDto): Promise<ChannelMonitorDto> {
  return invokeNonIdempotent<ChannelMonitorDto>("create_channel_monitor", { input });
}

export function updateChannelMonitor(input: UpdateChannelMonitorInputDto): Promise<ChannelMonitorDto> {
  return invokeCommand<ChannelMonitorDto>("update_channel_monitor", { input });
}

export function deleteChannelMonitor(input: ChannelMonitorMutationIdInputDto): Promise<void> {
  return invokeCommand<void>("delete_channel_monitor", { input });
}

export function createChannelMonitorTemplate(input: CreateChannelMonitorTemplateInputDto): Promise<ChannelMonitorRequestTemplateDto> {
  return invokeNonIdempotent<ChannelMonitorRequestTemplateDto>("create_channel_monitor_template", { input });
}

export function updateChannelMonitorTemplate(input: UpdateChannelMonitorTemplateInputDto): Promise<ChannelMonitorRequestTemplateDto> {
  return invokeCommand<ChannelMonitorRequestTemplateDto>("update_channel_monitor_template", { input });
}

export function duplicateChannelMonitorTemplate(input: ChannelMonitorMutationIdInputDto): Promise<ChannelMonitorRequestTemplateDto> {
  return invokeNonIdempotent<ChannelMonitorRequestTemplateDto>("duplicate_channel_monitor_template", { input });
}

export function deleteChannelMonitorTemplate(input: ChannelMonitorMutationIdInputDto): Promise<void> {
  return invokeCommand<void>("delete_channel_monitor_template", { input });
}

export function loadChannelStatusWorkspace(input: EmptyInputDto = {}): Promise<ChannelStatusWorkspaceDto> {
  return invokeCommand<ChannelStatusWorkspaceDto>("load_channel_status_workspace", { input });
}

export function runChannelMonitorNow(input: ChannelMonitorIdInputDto): Promise<ChannelMonitorRunDto[]> {
  return invokeNonIdempotent<ChannelMonitorRunDto[]>("run_channel_monitor_now", { input });
}

export function getRuntimeContractInfo(): Promise<RuntimeContractInfo> {
  return invokeCommand<RuntimeContractInfo>("get_runtime_contract_info");
}

export type StreamingSubscription = { close(): void };

export interface TypedStreamingAdapter<Event> {
  readonly eventSchemaVersion: number;
  open(onEvent: (event: Event) => void): StreamingSubscription;
}
