// @generated by repository IPC generator. Do not edit.
// generator version: 1
// IPC contract version: 1
// canonical hash: 64adfdee45bed2d91f5801ecf3e052f31170a4344dbdad32cbcb4f2a4f15bbfe

import { invoke, invokeNonIdempotent } from "@/lib/bridge/transport";

export type EmptyInputDto = Record<string, never>;

export type RoutingGroupFilter =
  | "all_groups"
  | "ungrouped_only"
  | { group_binding_id: string }
  | { group_id_hash: string }
  | { group_type: "gpt" | "claude" | "gemini" | "grok" | "image_generation" };

export type SchedulerAdvancedSettingsDto = {
  topK: number;
  multiplier: number;
  priority: number;
  load: number;
  queue: number;
  errorRate: number;
  ttft: number;
  quotaHeadroom: number;
  previousResponse: number;
  sessionSticky: number;
  multiplierMinConfidence: number;
  stickyWeighted: boolean;
  stickyEscape: boolean;
  stickyEscapeTtftMs: number;
  stickyEscapeErrorRate: number;
  stickySessionTtlSeconds: number;
  stickyResponseTtlSeconds: number;
  stickyMaxWaiting: number;
  stickyWaitTimeoutSeconds: number;
  fallbackMaxWaiting: number;
  fallbackWaitTimeoutSeconds: number;
};

export type RoutingStrategyInput =
  | "automatic_balanced"
  | "priority_fallback"
  | "stable_first"
  | "backup_only"
  | "cheap_first"
  | "cost_stable_first";

export type CollectorProxyModeInput = "direct" | "system" | "manual";

export type UpdateSettingsInputDto = {
  localProxyPort: number;
  defaultRoutingStrategy: RoutingStrategyInput;
  collectorProxyMode: CollectorProxyModeInput;
  collectorProxyUrl: string | null;
  maxRateMultiplier: number | null;
  defaultRoutingGroupFilter?: RoutingGroupFilter;
  schedulerAdvancedSettings?: SchedulerAdvancedSettingsDto | null;
  lowBalanceThresholdCny: number;
  collectorIntervalMinutes: number;
  balanceIntervalMinutes: number;
  groupRateIntervalMinutes: number;
  modelListIntervalMinutes: number;
  pricingRefreshIntervalMinutes: number;
  collectorTimeoutSeconds: number;
  collectorMaxConcurrency: number;
  allowDepletedFallback: boolean;
  developerModeEnabled: boolean;
  trayBehavior?: "close_to_tray" | "minimize_to_tray" | "disabled";
};

export type SettingsDto = {
  localProxyPort: number;
  localProxyStartOnLaunch: boolean;
  localKeyMasked: string;
  defaultRoutingStrategy: string;
  collectorProxyMode: string;
  collectorProxyUrl: string | null;
  maxRateMultiplier: number | null;
  defaultRoutingGroupFilter: RoutingGroupFilter;
  schedulerAdvancedSettings: SchedulerAdvancedSettingsDto;
  lowBalanceThresholdCny: number;
  collectorIntervalMinutes: number;
  balanceIntervalMinutes: number;
  groupRateIntervalMinutes: number;
  modelListIntervalMinutes: number;
  pricingRefreshIntervalMinutes: number;
  collectorTimeoutSeconds: number;
  collectorMaxConcurrency: number;
  allowDepletedFallback: boolean;
  developerModeEnabled: boolean;
  trayBehavior: string;
  dataDir: string;
  pendingDataDir: string | null;
  dataDirChangeRequiresRestart: boolean;
};

export type StationTypeInput = "sub2api" | "newapi" | "openai-compatible" | "custom";

export type StationProxyModeInput = "inherit" | "direct" | "system" | "manual";

export type CreateStationInputDto = {
  name: string;
  stationType: StationTypeInput;
  websiteUrl: string;
  apiBaseUrl: string;
  apiKey: string;
  collectorProxyMode: StationProxyModeInput;
  collectorProxyUrl: string | null;
  enabled: boolean;
  creditPerCny: number;
  lowBalanceThresholdCny: number | null;
  collectionIntervalMinutes: number;
  note: string | null;
};

export type UpdateStationInputDto = Omit<CreateStationInputDto, "apiKey"> & {
  id: string;
  apiKey: string | null;
};

export type DeleteStationInputDto = { id: string };

export type ReorderStationsInputDto = { stationIds: string[] };

export type StationDto = {
  id: string;
  name: string;
  stationType: string;
  websiteUrl: string;
  apiBaseUrl: string;
  endpointRevision: number;
  collectorProxyMode: string;
  collectorProxyUrl: string | null;
  apiKeyMasked: string;
  apiKeyPresent: boolean;
  keyCount: number;
  enabled: boolean;
  priority: number;
  creditPerCny: number;
  balanceRaw: number | null;
  balanceCny: number | null;
  lowBalanceThresholdCny: number | null;
  collectionIntervalMinutes: number;
  status: string;
  latencyMs: number | null;
  lastCheckedAt: string | null;
  lastPricingFetchedAt: string | null;
  note: string | null;
  createdAt: string;
  updatedAt: string;
};

export type RuntimeCapability =
  | "runtime_contract"
  | "data_recovery"
  | "settings"
  | "stations"
  | "station_keys"
  | "collectors"
  | "routing"
  | "proxy"
  | "channel_monitoring"
  | "pricing"
  | "change_events"
  | "capture"
  | "typed_streaming";

export type RuntimeContractInfo = {
  appVersion: string;
  ipcContractVersion: number;
  bindingHash: string;
  capabilities: RuntimeCapability[];
};

export type CommandErrorCode =
  | "invalid_input"
  | "not_found"
  | "conflict"
  | "permission_denied"
  | "runtime_unavailable"
  | "data_store_unavailable"
  | "external_unavailable"
  | "timeout"
  | "overloaded"
  | "unsupported"
  | "internal";

export type PublicFieldError = {
  field: string;
  code: string;
  message: string;
};

export type PublicErrorDetails =
  | { kind: "validation"; fields: PublicFieldError[] }
  | { kind: "conflict"; resource: string; currentRevision: string | null }
  | { kind: "retry"; retryAfterMs: number | null }
  | { kind: "external"; provider: string | null; upstreamStatus: number | null };

export type CommandError = {
  code: CommandErrorCode;
  message: string;
  retryable: boolean;
  details: PublicErrorDetails | null;
  correlationId: string | null;
};

export type IpcCommand =
  | "activate_data_store_candidate"
  | "app_status"
  | "bind_remote_station_key"
  | "choose_data_dir"
  | "cleanup_before_update"
  | "clear_capture_session"
  | "clear_change_events"
  | "clear_request_logs"
  | "clear_station_credentials"
  | "close_capture_session"
  | "collect_station_info"
  | "collect_station_task"
  | "collect_sub2api_station"
  | "create_channel_monitor"
  | "create_channel_monitor_template"
  | "create_local_station_key_from_remote"
  | "create_new_data_store"
  | "create_remote_station_key"
  | "create_station"
  | "create_station_key"
  | "delete_channel_monitor"
  | "delete_channel_monitor_template"
  | "delete_model_alias"
  | "delete_pricing_rule"
  | "delete_station"
  | "delete_station_key"
  | "detect_station_info"
  | "detect_sub2api_station"
  | "dismiss_change_event"
  | "duplicate_channel_monitor_template"
  | "export_data_store_diagnostic"
  | "finish_capture_session"
  | "finish_web_authorization_session"
  | "get_capture_session_status"
  | "get_data_store_startup_state"
  | "get_latest_collector_snapshot"
  | "get_local_access_key"
  | "get_proxy_status"
  | "get_remote_key_capability"
  | "get_runtime_contract_info"
  | "get_settings"
  | "get_station_credentials"
  | "get_station_key_capabilities"
  | "get_station_key_health"
  | "import_relay_pool_to_ccswitch"
  | "inspect_latest_update_manifest"
  | "list_balance_snapshots"
  | "list_balance_snapshots_for_station"
  | "list_change_events"
  | "list_change_events_for_station"
  | "list_channel_monitor_runs"
  | "list_channel_monitor_summaries"
  | "list_channel_monitor_templates"
  | "list_channel_monitors"
  | "list_channel_status_summaries"
  | "list_collector_runs"
  | "list_collector_snapshots"
  | "list_current_station_balance_snapshots"
  | "list_group_rate_records"
  | "list_key_pool_items"
  | "list_model_aliases"
  | "list_model_base_prices"
  | "list_pricing_rules"
  | "list_remote_station_keys"
  | "list_request_logs"
  | "list_station_endpoint_health"
  | "list_station_group_bindings"
  | "list_station_group_options"
  | "list_station_key_health"
  | "list_station_keys"
  | "list_stations"
  | "load_channel_status_workspace"
  | "load_local_routing_workspace"
  | "load_pricing_comparison_workspace"
  | "locate_data_store_candidate"
  | "mark_change_event_read"
  | "mark_change_events_read"
  | "open_data_store_backup_dir"
  | "open_external_url"
  | "ping_station_endpoint"
  | "prepare_local_proxy_for_update"
  | "record_capture_event"
  | "refresh_data_store_candidates"
  | "reorder_key_pool"
  | "reorder_local_routing_keys"
  | "reorder_station_keys"
  | "reorder_stations"
  | "reset_data_dir"
  | "reset_model_base_prices_to_builtins"
  | "resolve_change_event"
  | "resolve_station_key_pricing_context"
  | "restart_local_proxy"
  | "run_channel_monitor_now"
  | "save_station_key_with_defaults"
  | "scan_remote_station_keys"
  | "simulate_route"
  | "start_capture_session"
  | "start_local_proxy"
  | "stop_local_proxy"
  | "test_station_key_connectivity"
  | "test_station_login"
  | "test_station_login_input"
  | "unbind_remote_station_key"
  | "update_channel_monitor"
  | "update_channel_monitor_template"
  | "update_local_access_key"
  | "update_settings"
  | "update_station"
  | "update_station_credentials"
  | "update_station_key"
  | "update_station_key_capabilities"
  | "update_station_key_group_binding"
  | "update_station_session"
  | "updater_network_config"
  | "upsert_balance_snapshot"
  | "upsert_change_event"
  | "upsert_model_alias"
  | "upsert_model_base_price"
  | "upsert_pricing_rule"
  | "upsert_station_group_binding";

export const IPC_CONTRACT_VERSION = 1 as const;
export const IPC_BINDING_HASH = "64adfdee45bed2d91f5801ecf3e052f31170a4344dbdad32cbcb4f2a4f15bbfe" as const;

export function invokeCommand<T>(command: IpcCommand, args?: Record<string, unknown>): Promise<T> {
  return invoke<T>(command, args);
}

export function getSettings(input: EmptyInputDto = {}): Promise<SettingsDto> {
  return invokeCommand<SettingsDto>("get_settings", { input });
}

export function listStations(input: EmptyInputDto = {}): Promise<StationDto[]> {
  return invokeCommand<StationDto[]>("list_stations", { input });
}

export function updateSettings(input: UpdateSettingsInputDto): Promise<SettingsDto> {
  return invokeCommand<SettingsDto>("update_settings", { input });
}

export function createStation(input: CreateStationInputDto): Promise<StationDto> {
  return invokeNonIdempotent<StationDto>("create_station", { input });
}

export function updateStation(input: UpdateStationInputDto): Promise<StationDto> {
  return invokeCommand<StationDto>("update_station", { input });
}

export function deleteStation(input: DeleteStationInputDto): Promise<void> {
  return invokeCommand<void>("delete_station", { input });
}

export function reorderStations(input: ReorderStationsInputDto): Promise<StationDto[]> {
  return invokeCommand<StationDto[]>("reorder_stations", { input });
}

export function getRuntimeContractInfo(): Promise<RuntimeContractInfo> {
  return invokeCommand<RuntimeContractInfo>("get_runtime_contract_info");
}

export type StreamingSubscription = { close(): void };

export interface TypedStreamingAdapter<Event> {
  readonly eventSchemaVersion: number;
  open(onEvent: (event: Event) => void): StreamingSubscription;
}
