import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const inventoryScript = path.join(repoRoot, "scripts", "dead-code-inventory.mjs");
const tempRoots = [];

try {
  await expectPass(
    "clean production source",
    `
pub fn exported_contract() -> u8 {
    42
}
`,
  );

  await expectFailure(
    "ordinary dead function",
    `
fn unused_private_helper() -> u8 {
    42
}
`,
    /visible dead_code diagnostic group\(s\)/,
  );

  await expectFailure(
    "crate-level allow dead_code",
    `
#![allow(dead_code)]

fn hidden_by_crate_allow() -> u8 {
    42
}
`,
    /blanket allow\(dead_code\)/,
  );

  await expectFailure(
    "module-level allow dead_code",
    `
#[allow(dead_code)]
mod hidden_by_module_allow {
    fn helper() -> u8 {
        42
    }
}
`,
    /local allow\(dead_code\)/,
  );

  await expectFailure(
    "unregistered expect dead_code",
    `
#[expect(dead_code, reason = "legacy placeholder")]
fn hidden_by_unregistered_expect() -> u8 {
    42
}
`,
    /unregistered expect\(dead_code\)/,
  );

  await expectFailure(
    "test-support marker in default source",
    `
// test-support helper must not leak into the default production source set.
pub fn exported_contract() -> u8 {
    42
}
`,
    /test-support leakage/,
  );

  console.log("dead-code inventory policy fixtures passed");
} finally {
  for (const tempRoot of tempRoots) {
    await rm(tempRoot, { force: true, recursive: true });
  }
}

async function expectPass(name, libSource) {
  const root = await createFixtureProject(name, libSource);
  const result = runInventory(root);
  assert.equal(result.status, 0, `${name} should pass\n${result.output}`);
}

async function expectFailure(name, libSource, outputPattern) {
  const root = await createFixtureProject(name, libSource);
  const result = runInventory(root);
  assert.notEqual(result.status, 0, `${name} should fail`);
  assert.match(result.output, outputPattern, `${name} should report ${outputPattern}\n${result.output}`);
}

async function createFixtureProject(name, libSource) {
  const safeName = name.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  const root = await mkdtemp(path.join(tmpdir(), `relay-pool-${safeName}-`));
  tempRoots.push(root);
  const sourceRoot = path.join(root, "src-tauri", "src");
  await mkdir(sourceRoot, { recursive: true });
  await writeFile(
    path.join(root, "src-tauri", "Cargo.toml"),
    [
      "[package]",
      'name = "relay_pool_dead_code_fixture"',
      'version = "0.1.0"',
      'edition = "2021"',
      "",
      "[lib]",
      'path = "src/lib.rs"',
      "",
    ].join("\n"),
    "utf8",
  );
  await writeFile(
    path.join(root, "src-tauri", "Cargo.lock"),
    [
      "# This file is automatically @generated by Cargo.",
      "# It is not intended for manual editing.",
      "version = 4",
      "",
      "[[package]]",
      'name = "relay_pool_dead_code_fixture"',
      'version = "0.1.0"',
      "",
    ].join("\n"),
    "utf8",
  );
  await writeFile(path.join(sourceRoot, "lib.rs"), `${libSource.trim()}\n`, "utf8");
  return root;
}

function runInventory(cwd) {
  const result = spawnSync(process.execPath, [inventoryScript, "--mode", "ci", "--scope", "production"], {
    cwd,
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
  });
  return {
    status: result.status ?? 1,
    output: `${result.stdout ?? ""}${result.stderr ?? ""}`,
  };
}
